// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6phQM87kxpP_DNlOTwr5_3lpmQnFkveo',
    appId: '1:629109182652:web:55ec9e0476b64b4fc280b9',
    messagingSenderId: '629109182652',
    projectId: 'countryapp-flutter',
    authDomain: 'countryapp-flutter.firebaseapp.com',
    storageBucket: 'countryapp-flutter.appspot.com',
    measurementId: 'G-Q8C3CQ1074',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYy9gsyVJWVCoo-dCIPlRPrPaME0Suf00',
    appId: '1:629109182652:android:0557d718490cafeac280b9',
    messagingSenderId: '629109182652',
    projectId: 'countryapp-flutter',
    storageBucket: 'countryapp-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA65Lew3IXwgca3exOtUMWz_NgVw0UBXfk',
    appId: '1:629109182652:ios:6194ca295e0093b4c280b9',
    messagingSenderId: '629109182652',
    projectId: 'countryapp-flutter',
    storageBucket: 'countryapp-flutter.appspot.com',
    iosClientId: '629109182652-fs8scudcu9ch8p2ggrauui2p32qf5obq.apps.googleusercontent.com',
    iosBundleId: 'com.example.countryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA65Lew3IXwgca3exOtUMWz_NgVw0UBXfk',
    appId: '1:629109182652:ios:3b1bc775ba0e8d26c280b9',
    messagingSenderId: '629109182652',
    projectId: 'countryapp-flutter',
    storageBucket: 'countryapp-flutter.appspot.com',
    iosClientId: '629109182652-7f0tioc1v1vvh5a1nj448ieca4d273bp.apps.googleusercontent.com',
    iosBundleId: 'com.example.countryApp.RunnerTests',
  );
}
